# Generated by Django 3.2.4 on 2021-06-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoryassignedvirtualtype'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, related_name='_articles_articlepage_secondary_categories_+', to='categories.CategoryPage'),
        ),
    ]
