# Generated by Django 3.2.4 on 2021-06-16 11:36

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoryassignedvirtualtype'),
        ('articles', '0002_alter_articlepage_secondary_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='primary_category',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categorypage'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='secondary_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_articles_articlepage_secondary_categories_+', to='categories.CategoryPage'),
        ),
    ]
