# Generated by Django 3.2.4 on 2021-06-16 11:59

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categoryassignedvirtualtype'),
        ('articles', '0003_auto_20210616_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='articlepage',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='primary_category',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categorypage', verbose_name='Primary category'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='secondary_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='_articles_articlepage_secondary_categories_+', to='categories.CategoryPage', verbose_name='Secondary categories'),
        ),
    ]
